# Generated by Django 4.2.4 on 2023-09-20 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_post_postadmin_account_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postadmin',
        ),
    ]
