# Generated by Django 4.2.4 on 2023-10-10 20:36

from django.db import migrations
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default=django.utils.timezone.now, force_format=None, keep_meta=True, quality=100, scale=None, size=[600, 400], upload_to='post_images/'),
            preserve_default=False,
        ),
    ]
