# Generated by Django 4.2.4 on 2023-10-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0005_post_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_file',
        ),
    ]
