# Generated by Django 4.2.4 on 2023-10-20 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0007_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='save',
            field=models.ManyToManyField(related_name='save_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
