# Generated by Django 4.2.4 on 2023-10-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0009_alter_post_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='save',
            new_name='save_post',
        ),
    ]
