# Generated by Django 4.2.4 on 2023-10-21 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0010_rename_save_post_save_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='save_post',
            new_name='saved',
        ),
    ]
