# Generated by Django 4.2.4 on 2023-10-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0012_contact_user_following_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
