# Generated by Django 4.2.4 on 2023-11-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0018_post_total_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-total_likes'], name='socialapp_p_total_l_2187a6_idx'),
        ),
    ]
